### ISSUE TITLE
Found a typo and wrong description on Part2

### ISSUE THREAD

**Issue by jetulis** [IBM/Create-BlockchainNetwork-IBPV20#6]
> such as consensus and membership services, to be plug-and-playIn
> 
> Part 2, we will explore more about creating a complex network with multiple participants and using Access Control Rules (ACL) to provide them network access permissions. In this journey, you will run Hyperledger Fabric on the Cloud.

1. plug-and-play. In Part 2, ~~~

2. Part 2 is still done on Hyperledger Composer which is running on local environment, not Cloud nor Fabric.

Any plan to convert this to Fabric version ?

**Comment by ash7594** [comment]
Part 2 code pattern link is now changed to the updated Fabric pattern
