### ISSUE TITLE
Not able to setup VSCode Extension

### ISSUE THREAD

**Issue by maheshwarishikha** [IBM/Create-BlockchainNetwork-IBPV20#7]
When I am trying VSCode extension, after setting up GOPATH I get error as:
"The Go smart contract is not a subdirectory of the path specified by the environment variable GOPATH. Please correct the environment variable GOPATH."

Copied installed Go in a directory and placed chaincode inside that. Still it shows the same error. Please help.

**Comment by ash7594** [comment]
Hi,
Please follow step 2 here: https://github.com/ljbennett62/PublicRegulationFabric-Food-IBPV20#1-clone-git-repository

This should fix your issue.

**Comment by maheshwarishikha** [comment]
Thanks.
